# https://doc.traefik.io/traefik/reference/static-configuration/file/

global:
  checkNewVersion: true
  sendAnonymousUsage: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443

  postgres:
    address: :5432

log:
  filePath: /var/log/traefik.json
  level: DEBUG
  format: json

accessLog:
  filePath: /var/log/access.json
  format: json

api:
  insecure: true
  dashboard: true

ping:
  entryPoint: traefik

providers:
  file:
    filename: /etc/traefik/provider.yml
  docker:
    exposedByDefault: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: user@email.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
